// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/caporal7/jroom/common/java/proto/JRoom.proto

package com.caporal7.jroom.common.java.protoc;

public final class JRoomProtos {
  private JRoomProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * message type 
   * </pre>
   *
   * Protobuf enum {@code jroom.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INVALID = 0;</code>
     */
    INVALID(0),
    /**
     * <code>JOIN_CONFERENCE_PROB = 1;</code>
     */
    JOIN_CONFERENCE_PROB(1),
    /**
     * <code>JOIN_CONFERENCE_AUTH = 2;</code>
     */
    JOIN_CONFERENCE_AUTH(2),
    ;

    /**
     * <code>INVALID = 0;</code>
     */
    public static final int INVALID_VALUE = 0;
    /**
     * <code>JOIN_CONFERENCE_PROB = 1;</code>
     */
    public static final int JOIN_CONFERENCE_PROB_VALUE = 1;
    /**
     * <code>JOIN_CONFERENCE_AUTH = 2;</code>
     */
    public static final int JOIN_CONFERENCE_AUTH_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return INVALID;
        case 1: return JOIN_CONFERENCE_PROB;
        case 2: return JOIN_CONFERENCE_AUTH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.caporal7.jroom.common.java.protoc.JRoomProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jroom.Type)
  }

  public interface JRoomRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jroom.JRoomRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * JRoom request type 
     * </pre>
     *
     * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     * JRoom request type 
     * </pre>
     *
     * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
     * @return The type.
     */
    com.caporal7.jroom.common.java.protoc.JRoomProtos.Type getType();

    /**
     * <pre>
     * JRoom join conference request 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
     * @return Whether the joinConferenceProb field is set.
     */
    boolean hasJoinConferenceProb();
    /**
     * <pre>
     * JRoom join conference request 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
     * @return The joinConferenceProb.
     */
    com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest getJoinConferenceProb();
    /**
     * <pre>
     * JRoom join conference request 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
     */
    com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequestOrBuilder getJoinConferenceProbOrBuilder();

    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
     * @return Whether the joinConferenceAuth field is set.
     */
    boolean hasJoinConferenceAuth();
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
     * @return The joinConferenceAuth.
     */
    com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest getJoinConferenceAuth();
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
     */
    com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequestOrBuilder getJoinConferenceAuthOrBuilder();
  }
  /**
   * <pre>
   * The request message 
   * </pre>
   *
   * Protobuf type {@code jroom.JRoomRequest}
   */
  public  static final class JRoomRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jroom.JRoomRequest)
      JRoomRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JRoomRequest.newBuilder() to construct.
    private JRoomRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JRoomRequest() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JRoomRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JRoomRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.caporal7.jroom.common.java.protoc.JRoomProtos.Type value = com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = joinConferenceProb_.toBuilder();
              }
              joinConferenceProb_ = input.readMessage(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(joinConferenceProb_);
                joinConferenceProb_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = joinConferenceAuth_.toBuilder();
              }
              joinConferenceAuth_ = input.readMessage(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(joinConferenceAuth_);
                joinConferenceAuth_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest.class, com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * JRoom request type 
     * </pre>
     *
     * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * JRoom request type 
     * </pre>
     *
     * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
     * @return The type.
     */
    public com.caporal7.jroom.common.java.protoc.JRoomProtos.Type getType() {
      @SuppressWarnings("deprecation")
      com.caporal7.jroom.common.java.protoc.JRoomProtos.Type result = com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.valueOf(type_);
      return result == null ? com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.INVALID : result;
    }

    public static final int JOIN_CONFERENCE_PROB_FIELD_NUMBER = 2;
    private com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest joinConferenceProb_;
    /**
     * <pre>
     * JRoom join conference request 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
     * @return Whether the joinConferenceProb field is set.
     */
    public boolean hasJoinConferenceProb() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * JRoom join conference request 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
     * @return The joinConferenceProb.
     */
    public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest getJoinConferenceProb() {
      return joinConferenceProb_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.getDefaultInstance() : joinConferenceProb_;
    }
    /**
     * <pre>
     * JRoom join conference request 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
     */
    public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequestOrBuilder getJoinConferenceProbOrBuilder() {
      return joinConferenceProb_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.getDefaultInstance() : joinConferenceProb_;
    }

    public static final int JOIN_CONFERENCE_AUTH_FIELD_NUMBER = 3;
    private com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest joinConferenceAuth_;
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
     * @return Whether the joinConferenceAuth field is set.
     */
    public boolean hasJoinConferenceAuth() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
     * @return The joinConferenceAuth.
     */
    public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest getJoinConferenceAuth() {
      return joinConferenceAuth_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.getDefaultInstance() : joinConferenceAuth_;
    }
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
     */
    public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequestOrBuilder getJoinConferenceAuthOrBuilder() {
      return joinConferenceAuth_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.getDefaultInstance() : joinConferenceAuth_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getJoinConferenceProb());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getJoinConferenceAuth());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getJoinConferenceProb());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getJoinConferenceAuth());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest)) {
        return super.equals(obj);
      }
      com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest other = (com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasJoinConferenceProb() != other.hasJoinConferenceProb()) return false;
      if (hasJoinConferenceProb()) {
        if (!getJoinConferenceProb()
            .equals(other.getJoinConferenceProb())) return false;
      }
      if (hasJoinConferenceAuth() != other.hasJoinConferenceAuth()) return false;
      if (hasJoinConferenceAuth()) {
        if (!getJoinConferenceAuth()
            .equals(other.getJoinConferenceAuth())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasJoinConferenceProb()) {
        hash = (37 * hash) + JOIN_CONFERENCE_PROB_FIELD_NUMBER;
        hash = (53 * hash) + getJoinConferenceProb().hashCode();
      }
      if (hasJoinConferenceAuth()) {
        hash = (37 * hash) + JOIN_CONFERENCE_AUTH_FIELD_NUMBER;
        hash = (53 * hash) + getJoinConferenceAuth().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message 
     * </pre>
     *
     * Protobuf type {@code jroom.JRoomRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jroom.JRoomRequest)
        com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest.class, com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest.Builder.class);
      }

      // Construct using com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getJoinConferenceProbFieldBuilder();
          getJoinConferenceAuthFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (joinConferenceProbBuilder_ == null) {
          joinConferenceProb_ = null;
        } else {
          joinConferenceProbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (joinConferenceAuthBuilder_ == null) {
          joinConferenceAuth_ = null;
        } else {
          joinConferenceAuthBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomRequest_descriptor;
      }

      @java.lang.Override
      public com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest getDefaultInstanceForType() {
        return com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest build() {
        com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest buildPartial() {
        com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest result = new com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (joinConferenceProbBuilder_ == null) {
            result.joinConferenceProb_ = joinConferenceProb_;
          } else {
            result.joinConferenceProb_ = joinConferenceProbBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (joinConferenceAuthBuilder_ == null) {
            result.joinConferenceAuth_ = joinConferenceAuth_;
          } else {
            result.joinConferenceAuth_ = joinConferenceAuthBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest) {
          return mergeFrom((com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest other) {
        if (other == com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasJoinConferenceProb()) {
          mergeJoinConferenceProb(other.getJoinConferenceProb());
        }
        if (other.hasJoinConferenceAuth()) {
          mergeJoinConferenceAuth(other.getJoinConferenceAuth());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <pre>
       * JRoom request type 
       * </pre>
       *
       * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * JRoom request type 
       * </pre>
       *
       * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
       * @return The type.
       */
      public com.caporal7.jroom.common.java.protoc.JRoomProtos.Type getType() {
        @SuppressWarnings("deprecation")
        com.caporal7.jroom.common.java.protoc.JRoomProtos.Type result = com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.valueOf(type_);
        return result == null ? com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.INVALID : result;
      }
      /**
       * <pre>
       * JRoom request type 
       * </pre>
       *
       * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.caporal7.jroom.common.java.protoc.JRoomProtos.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JRoom request type 
       * </pre>
       *
       * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest joinConferenceProb_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequestOrBuilder> joinConferenceProbBuilder_;
      /**
       * <pre>
       * JRoom join conference request 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
       * @return Whether the joinConferenceProb field is set.
       */
      public boolean hasJoinConferenceProb() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * JRoom join conference request 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
       * @return The joinConferenceProb.
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest getJoinConferenceProb() {
        if (joinConferenceProbBuilder_ == null) {
          return joinConferenceProb_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.getDefaultInstance() : joinConferenceProb_;
        } else {
          return joinConferenceProbBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * JRoom join conference request 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
       */
      public Builder setJoinConferenceProb(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest value) {
        if (joinConferenceProbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          joinConferenceProb_ = value;
          onChanged();
        } else {
          joinConferenceProbBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * JRoom join conference request 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
       */
      public Builder setJoinConferenceProb(
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.Builder builderForValue) {
        if (joinConferenceProbBuilder_ == null) {
          joinConferenceProb_ = builderForValue.build();
          onChanged();
        } else {
          joinConferenceProbBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * JRoom join conference request 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
       */
      public Builder mergeJoinConferenceProb(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest value) {
        if (joinConferenceProbBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              joinConferenceProb_ != null &&
              joinConferenceProb_ != com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.getDefaultInstance()) {
            joinConferenceProb_ =
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.newBuilder(joinConferenceProb_).mergeFrom(value).buildPartial();
          } else {
            joinConferenceProb_ = value;
          }
          onChanged();
        } else {
          joinConferenceProbBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * JRoom join conference request 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
       */
      public Builder clearJoinConferenceProb() {
        if (joinConferenceProbBuilder_ == null) {
          joinConferenceProb_ = null;
          onChanged();
        } else {
          joinConferenceProbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       * JRoom join conference request 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.Builder getJoinConferenceProbBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getJoinConferenceProbFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * JRoom join conference request 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequestOrBuilder getJoinConferenceProbOrBuilder() {
        if (joinConferenceProbBuilder_ != null) {
          return joinConferenceProbBuilder_.getMessageOrBuilder();
        } else {
          return joinConferenceProb_ == null ?
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.getDefaultInstance() : joinConferenceProb_;
        }
      }
      /**
       * <pre>
       * JRoom join conference request 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeRequest join_conference_prob = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequestOrBuilder> 
          getJoinConferenceProbFieldBuilder() {
        if (joinConferenceProbBuilder_ == null) {
          joinConferenceProbBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequest.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeRequestOrBuilder>(
                  getJoinConferenceProb(),
                  getParentForChildren(),
                  isClean());
          joinConferenceProb_ = null;
        }
        return joinConferenceProbBuilder_;
      }

      private com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest joinConferenceAuth_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequestOrBuilder> joinConferenceAuthBuilder_;
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
       * @return Whether the joinConferenceAuth field is set.
       */
      public boolean hasJoinConferenceAuth() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
       * @return The joinConferenceAuth.
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest getJoinConferenceAuth() {
        if (joinConferenceAuthBuilder_ == null) {
          return joinConferenceAuth_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.getDefaultInstance() : joinConferenceAuth_;
        } else {
          return joinConferenceAuthBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
       */
      public Builder setJoinConferenceAuth(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest value) {
        if (joinConferenceAuthBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          joinConferenceAuth_ = value;
          onChanged();
        } else {
          joinConferenceAuthBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
       */
      public Builder setJoinConferenceAuth(
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.Builder builderForValue) {
        if (joinConferenceAuthBuilder_ == null) {
          joinConferenceAuth_ = builderForValue.build();
          onChanged();
        } else {
          joinConferenceAuthBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
       */
      public Builder mergeJoinConferenceAuth(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest value) {
        if (joinConferenceAuthBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              joinConferenceAuth_ != null &&
              joinConferenceAuth_ != com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.getDefaultInstance()) {
            joinConferenceAuth_ =
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.newBuilder(joinConferenceAuth_).mergeFrom(value).buildPartial();
          } else {
            joinConferenceAuth_ = value;
          }
          onChanged();
        } else {
          joinConferenceAuthBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
       */
      public Builder clearJoinConferenceAuth() {
        if (joinConferenceAuthBuilder_ == null) {
          joinConferenceAuth_ = null;
          onChanged();
        } else {
          joinConferenceAuthBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.Builder getJoinConferenceAuthBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getJoinConferenceAuthFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequestOrBuilder getJoinConferenceAuthOrBuilder() {
        if (joinConferenceAuthBuilder_ != null) {
          return joinConferenceAuthBuilder_.getMessageOrBuilder();
        } else {
          return joinConferenceAuth_ == null ?
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.getDefaultInstance() : joinConferenceAuth_;
        }
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthRequest join_conference_auth = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequestOrBuilder> 
          getJoinConferenceAuthFieldBuilder() {
        if (joinConferenceAuthBuilder_ == null) {
          joinConferenceAuthBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequest.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthRequestOrBuilder>(
                  getJoinConferenceAuth(),
                  getParentForChildren(),
                  isClean());
          joinConferenceAuth_ = null;
        }
        return joinConferenceAuthBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jroom.JRoomRequest)
    }

    // @@protoc_insertion_point(class_scope:jroom.JRoomRequest)
    private static final com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest();
    }

    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<JRoomRequest>
        PARSER = new com.google.protobuf.AbstractParser<JRoomRequest>() {
      @java.lang.Override
      public JRoomRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JRoomRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JRoomRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JRoomRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JRoomResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jroom.JRoomResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * JRoom response type 
     * </pre>
     *
     * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     * JRoom response type 
     * </pre>
     *
     * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
     * @return The type.
     */
    com.caporal7.jroom.common.java.protoc.JRoomProtos.Type getType();

    /**
     * <pre>
     * JRoom join conference response 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
     * @return Whether the joinConferenceProb field is set.
     */
    boolean hasJoinConferenceProb();
    /**
     * <pre>
     * JRoom join conference response 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
     * @return The joinConferenceProb.
     */
    com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse getJoinConferenceProb();
    /**
     * <pre>
     * JRoom join conference response 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
     */
    com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponseOrBuilder getJoinConferenceProbOrBuilder();

    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
     * @return Whether the joinConferenceAuth field is set.
     */
    boolean hasJoinConferenceAuth();
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
     * @return The joinConferenceAuth.
     */
    com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse getJoinConferenceAuth();
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
     */
    com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponseOrBuilder getJoinConferenceAuthOrBuilder();
  }
  /**
   * <pre>
   * The response message 
   * </pre>
   *
   * Protobuf type {@code jroom.JRoomResponse}
   */
  public  static final class JRoomResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jroom.JRoomResponse)
      JRoomResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JRoomResponse.newBuilder() to construct.
    private JRoomResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JRoomResponse() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JRoomResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JRoomResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.caporal7.jroom.common.java.protoc.JRoomProtos.Type value = com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = joinConferenceProb_.toBuilder();
              }
              joinConferenceProb_ = input.readMessage(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(joinConferenceProb_);
                joinConferenceProb_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = joinConferenceAuth_.toBuilder();
              }
              joinConferenceAuth_ = input.readMessage(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(joinConferenceAuth_);
                joinConferenceAuth_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse.class, com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * JRoom response type 
     * </pre>
     *
     * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * JRoom response type 
     * </pre>
     *
     * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
     * @return The type.
     */
    public com.caporal7.jroom.common.java.protoc.JRoomProtos.Type getType() {
      @SuppressWarnings("deprecation")
      com.caporal7.jroom.common.java.protoc.JRoomProtos.Type result = com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.valueOf(type_);
      return result == null ? com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.INVALID : result;
    }

    public static final int JOIN_CONFERENCE_PROB_FIELD_NUMBER = 2;
    private com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse joinConferenceProb_;
    /**
     * <pre>
     * JRoom join conference response 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
     * @return Whether the joinConferenceProb field is set.
     */
    public boolean hasJoinConferenceProb() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * JRoom join conference response 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
     * @return The joinConferenceProb.
     */
    public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse getJoinConferenceProb() {
      return joinConferenceProb_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.getDefaultInstance() : joinConferenceProb_;
    }
    /**
     * <pre>
     * JRoom join conference response 
     * </pre>
     *
     * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
     */
    public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponseOrBuilder getJoinConferenceProbOrBuilder() {
      return joinConferenceProb_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.getDefaultInstance() : joinConferenceProb_;
    }

    public static final int JOIN_CONFERENCE_AUTH_FIELD_NUMBER = 3;
    private com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse joinConferenceAuth_;
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
     * @return Whether the joinConferenceAuth field is set.
     */
    public boolean hasJoinConferenceAuth() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
     * @return The joinConferenceAuth.
     */
    public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse getJoinConferenceAuth() {
      return joinConferenceAuth_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.getDefaultInstance() : joinConferenceAuth_;
    }
    /**
     * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
     */
    public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponseOrBuilder getJoinConferenceAuthOrBuilder() {
      return joinConferenceAuth_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.getDefaultInstance() : joinConferenceAuth_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getJoinConferenceProb());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getJoinConferenceAuth());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getJoinConferenceProb());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getJoinConferenceAuth());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse)) {
        return super.equals(obj);
      }
      com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse other = (com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasJoinConferenceProb() != other.hasJoinConferenceProb()) return false;
      if (hasJoinConferenceProb()) {
        if (!getJoinConferenceProb()
            .equals(other.getJoinConferenceProb())) return false;
      }
      if (hasJoinConferenceAuth() != other.hasJoinConferenceAuth()) return false;
      if (hasJoinConferenceAuth()) {
        if (!getJoinConferenceAuth()
            .equals(other.getJoinConferenceAuth())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasJoinConferenceProb()) {
        hash = (37 * hash) + JOIN_CONFERENCE_PROB_FIELD_NUMBER;
        hash = (53 * hash) + getJoinConferenceProb().hashCode();
      }
      if (hasJoinConferenceAuth()) {
        hash = (37 * hash) + JOIN_CONFERENCE_AUTH_FIELD_NUMBER;
        hash = (53 * hash) + getJoinConferenceAuth().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message 
     * </pre>
     *
     * Protobuf type {@code jroom.JRoomResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jroom.JRoomResponse)
        com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse.class, com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse.Builder.class);
      }

      // Construct using com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getJoinConferenceProbFieldBuilder();
          getJoinConferenceAuthFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (joinConferenceProbBuilder_ == null) {
          joinConferenceProb_ = null;
        } else {
          joinConferenceProbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (joinConferenceAuthBuilder_ == null) {
          joinConferenceAuth_ = null;
        } else {
          joinConferenceAuthBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caporal7.jroom.common.java.protoc.JRoomProtos.internal_static_jroom_JRoomResponse_descriptor;
      }

      @java.lang.Override
      public com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse getDefaultInstanceForType() {
        return com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse build() {
        com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse buildPartial() {
        com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse result = new com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (joinConferenceProbBuilder_ == null) {
            result.joinConferenceProb_ = joinConferenceProb_;
          } else {
            result.joinConferenceProb_ = joinConferenceProbBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (joinConferenceAuthBuilder_ == null) {
            result.joinConferenceAuth_ = joinConferenceAuth_;
          } else {
            result.joinConferenceAuth_ = joinConferenceAuthBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse) {
          return mergeFrom((com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse other) {
        if (other == com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasJoinConferenceProb()) {
          mergeJoinConferenceProb(other.getJoinConferenceProb());
        }
        if (other.hasJoinConferenceAuth()) {
          mergeJoinConferenceAuth(other.getJoinConferenceAuth());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <pre>
       * JRoom response type 
       * </pre>
       *
       * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * JRoom response type 
       * </pre>
       *
       * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
       * @return The type.
       */
      public com.caporal7.jroom.common.java.protoc.JRoomProtos.Type getType() {
        @SuppressWarnings("deprecation")
        com.caporal7.jroom.common.java.protoc.JRoomProtos.Type result = com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.valueOf(type_);
        return result == null ? com.caporal7.jroom.common.java.protoc.JRoomProtos.Type.INVALID : result;
      }
      /**
       * <pre>
       * JRoom response type 
       * </pre>
       *
       * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.caporal7.jroom.common.java.protoc.JRoomProtos.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JRoom response type 
       * </pre>
       *
       * <code>optional .jroom.Type type = 1 [default = INVALID];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse joinConferenceProb_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponseOrBuilder> joinConferenceProbBuilder_;
      /**
       * <pre>
       * JRoom join conference response 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
       * @return Whether the joinConferenceProb field is set.
       */
      public boolean hasJoinConferenceProb() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * JRoom join conference response 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
       * @return The joinConferenceProb.
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse getJoinConferenceProb() {
        if (joinConferenceProbBuilder_ == null) {
          return joinConferenceProb_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.getDefaultInstance() : joinConferenceProb_;
        } else {
          return joinConferenceProbBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * JRoom join conference response 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
       */
      public Builder setJoinConferenceProb(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse value) {
        if (joinConferenceProbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          joinConferenceProb_ = value;
          onChanged();
        } else {
          joinConferenceProbBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * JRoom join conference response 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
       */
      public Builder setJoinConferenceProb(
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.Builder builderForValue) {
        if (joinConferenceProbBuilder_ == null) {
          joinConferenceProb_ = builderForValue.build();
          onChanged();
        } else {
          joinConferenceProbBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * JRoom join conference response 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
       */
      public Builder mergeJoinConferenceProb(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse value) {
        if (joinConferenceProbBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              joinConferenceProb_ != null &&
              joinConferenceProb_ != com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.getDefaultInstance()) {
            joinConferenceProb_ =
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.newBuilder(joinConferenceProb_).mergeFrom(value).buildPartial();
          } else {
            joinConferenceProb_ = value;
          }
          onChanged();
        } else {
          joinConferenceProbBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * JRoom join conference response 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
       */
      public Builder clearJoinConferenceProb() {
        if (joinConferenceProbBuilder_ == null) {
          joinConferenceProb_ = null;
          onChanged();
        } else {
          joinConferenceProbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       * JRoom join conference response 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.Builder getJoinConferenceProbBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getJoinConferenceProbFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * JRoom join conference response 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponseOrBuilder getJoinConferenceProbOrBuilder() {
        if (joinConferenceProbBuilder_ != null) {
          return joinConferenceProbBuilder_.getMessageOrBuilder();
        } else {
          return joinConferenceProb_ == null ?
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.getDefaultInstance() : joinConferenceProb_;
        }
      }
      /**
       * <pre>
       * JRoom join conference response 
       * </pre>
       *
       * <code>optional .jroom.JRoomJoinConferenceProbeResponse join_conference_prob = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponseOrBuilder> 
          getJoinConferenceProbFieldBuilder() {
        if (joinConferenceProbBuilder_ == null) {
          joinConferenceProbBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponse.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceProbeResponseOrBuilder>(
                  getJoinConferenceProb(),
                  getParentForChildren(),
                  isClean());
          joinConferenceProb_ = null;
        }
        return joinConferenceProbBuilder_;
      }

      private com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse joinConferenceAuth_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponseOrBuilder> joinConferenceAuthBuilder_;
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
       * @return Whether the joinConferenceAuth field is set.
       */
      public boolean hasJoinConferenceAuth() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
       * @return The joinConferenceAuth.
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse getJoinConferenceAuth() {
        if (joinConferenceAuthBuilder_ == null) {
          return joinConferenceAuth_ == null ? com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.getDefaultInstance() : joinConferenceAuth_;
        } else {
          return joinConferenceAuthBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
       */
      public Builder setJoinConferenceAuth(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse value) {
        if (joinConferenceAuthBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          joinConferenceAuth_ = value;
          onChanged();
        } else {
          joinConferenceAuthBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
       */
      public Builder setJoinConferenceAuth(
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.Builder builderForValue) {
        if (joinConferenceAuthBuilder_ == null) {
          joinConferenceAuth_ = builderForValue.build();
          onChanged();
        } else {
          joinConferenceAuthBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
       */
      public Builder mergeJoinConferenceAuth(com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse value) {
        if (joinConferenceAuthBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              joinConferenceAuth_ != null &&
              joinConferenceAuth_ != com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.getDefaultInstance()) {
            joinConferenceAuth_ =
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.newBuilder(joinConferenceAuth_).mergeFrom(value).buildPartial();
          } else {
            joinConferenceAuth_ = value;
          }
          onChanged();
        } else {
          joinConferenceAuthBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
       */
      public Builder clearJoinConferenceAuth() {
        if (joinConferenceAuthBuilder_ == null) {
          joinConferenceAuth_ = null;
          onChanged();
        } else {
          joinConferenceAuthBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.Builder getJoinConferenceAuthBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getJoinConferenceAuthFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
       */
      public com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponseOrBuilder getJoinConferenceAuthOrBuilder() {
        if (joinConferenceAuthBuilder_ != null) {
          return joinConferenceAuthBuilder_.getMessageOrBuilder();
        } else {
          return joinConferenceAuth_ == null ?
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.getDefaultInstance() : joinConferenceAuth_;
        }
      }
      /**
       * <code>optional .jroom.JRoomJoinConferenceAuthResponse join_conference_auth = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponseOrBuilder> 
          getJoinConferenceAuthFieldBuilder() {
        if (joinConferenceAuthBuilder_ == null) {
          joinConferenceAuthBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponse.Builder, com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.JRoomJoinConferenceAuthResponseOrBuilder>(
                  getJoinConferenceAuth(),
                  getParentForChildren(),
                  isClean());
          joinConferenceAuth_ = null;
        }
        return joinConferenceAuthBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jroom.JRoomResponse)
    }

    // @@protoc_insertion_point(class_scope:jroom.JRoomResponse)
    private static final com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse();
    }

    public static com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<JRoomResponse>
        PARSER = new com.google.protobuf.AbstractParser<JRoomResponse>() {
      @java.lang.Override
      public JRoomResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JRoomResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JRoomResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JRoomResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.caporal7.jroom.common.java.protoc.JRoomProtos.JRoomResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jroom_JRoomRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jroom_JRoomRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jroom_JRoomResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jroom_JRoomResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0com/caporal7/jroom/common/java/proto/J" +
      "Room.proto\022\005jroom\032>com/caporal7/jroom/co" +
      "mmon/java/proto/JRoomJoinConference.prot" +
      "o\"\275\001\n\014JRoomRequest\022\"\n\004type\030\001 \001(\0162\013.jroom" +
      ".Type:\007INVALID\022D\n\024join_conference_prob\030\002" +
      " \001(\0132&.jroom.JRoomJoinConferenceProbeReq" +
      "uest\022C\n\024join_conference_auth\030\003 \001(\0132%.jro" +
      "om.JRoomJoinConferenceAuthRequest\"\300\001\n\rJR" +
      "oomResponse\022\"\n\004type\030\001 \001(\0162\013.jroom.Type:\007" +
      "INVALID\022E\n\024join_conference_prob\030\002 \001(\0132\'." +
      "jroom.JRoomJoinConferenceProbeResponse\022D" +
      "\n\024join_conference_auth\030\003 \001(\0132&.jroom.JRo" +
      "omJoinConferenceAuthResponse*G\n\004Type\022\013\n\007" +
      "INVALID\020\000\022\030\n\024JOIN_CONFERENCE_PROB\020\001\022\030\n\024J" +
      "OIN_CONFERENCE_AUTH\020\002B4\n%com.caporal7.jr" +
      "oom.common.java.protocB\013JRoomProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.getDescriptor(),
        });
    internal_static_jroom_JRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jroom_JRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jroom_JRoomRequest_descriptor,
        new java.lang.String[] { "Type", "JoinConferenceProb", "JoinConferenceAuth", });
    internal_static_jroom_JRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jroom_JRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jroom_JRoomResponse_descriptor,
        new java.lang.String[] { "Type", "JoinConferenceProb", "JoinConferenceAuth", });
    com.caporal7.jroom.common.java.protoc.JRoomJoinConferenceProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
